### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JackChestnut** [cj1128/annotated-lyrics#1]
Error info like this:

(node:7772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'content' of undefined
    at parseLyric (C:\Users\Lenovo\jp.js:31:18)
    at genPDF (C:\Users\Lenovo\jp.js:116:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async C:\Users\Lenovo\main.js:45:7
(node:7772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cj1128** [comment]
I believe the problem is line splitting in Windows. The script only considered `\n` which was not going to work in Windows.

I fixed this problem please give it another try. 
https://github.com/cj1128/annotated-lyrics/blob/master/jp.js#L18

**Comment by JackChestnut** [comment]
Still having the problem... :(
So do I have really have to do this on Linux?
